const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Behaviors.destroy,
		C3.Plugins.NinePatch,
		C3.Plugins.Arr,
		C3.Behaviors.Orbit,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Persist,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Arr.Acts.SetX,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.JavaScriptInEvents.Inventoryevents_Event2_Act1,
		C3.Plugins.System.Acts.RecreateInitialObjects,
		C3.JavaScriptInEvents.Inventoryevents_Event4_Act1,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.JavaScriptInEvents.Inventoryevents_Event7_Act3,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.JavaScriptInEvents.Titleandgameoverandhelpevents_Event1_Act11,
		C3.JavaScriptInEvents.Titleandgameoverandhelpevents_Event2_Act11
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Anchor: 0},
	{Score: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Mouse: 0},
	{Health: 0},
	{Bullet: 0},
	{Monster: 0},
	{Keyboard: 0},
	{Fade: 0},
	{Explosion: 0},
	{DestroyOutsideLayout: 0},
	{"9patch": 0},
	{InventoryGrid: 0},
	{DebugText: 0},
	{NewSpell: 0},
	{Wave: 0},
	{Text3: 0},
	{Orbit: 0},
	{Aoe: 0},
	{SpellsCurrentlyKnown: 0},
	{Button2: 0},
	{TiledBackground2: 0},
	{Button: 0},
	{Audio: 0},
	{SpellNumber: 0},
	{StartX: 0},
	{StartY: 0},
	{BeingPickedUp: 0},
	{Growing: 0},
	{DragDrop: 0},
	{Persist: 0},
	{Spell: 0},
	{SpellGrowthLimits: 0},
	{TimesSpellsUsed: 0},
	{Array: 0},
	{SpellStages: 0},
	{OutsideOfGrid: 0},
	{Ice: 0},
	{Dist: 0},
	{Fireball: 0},
	{FireballExplosion: 0},
	{SpellDisplay: 0},
	{Lightning: 0},
	{LightningShock: 0},
	{TiledBackground3: 0},
	{SpellsEquipped: 0},
	{StartGame: 0},
	{Button3: 0},
	{Sparks: 0},
	{Lightning2: 0},
	{Sprite8: 0},
	{Wizard: 0},
	{Axe: 0},
	{IceShard: 0},
	{Slime: 0},
	{Sprite: 0},
	{TiledBackground4: 0},
	{HelpButton: 0},
	{Play_Button: 0},
	{Help_Button: 0},
	{Titlescreenbackground: 0},
	{LightningST: 0},
	{BulletST: 0},
	{AxeST: 0},
	{FireballST: 0},
	{IceShardST: 0},
	{GameOver: 0},
	{DeathBackground: 0},
	{Menu_Button: 0},
	{Text: 0},
	{Text2: 0},
	{ProgressBar: 0},
	{Text4: 0},
	{Text5: 0},
	{Spell1PickedUp: 0},
	{Spell2PickedUp: 0},
	{Spell3PickedUp: 0},
	{Spell4PickedUp: 0},
	{Spell5PickedUp: 0},
	{Spell6PickedUp: 0},
	{MonsterCount: 0},
	{SpellIsBullet: 0},
	{Spell0UsedCount: 0},
	{Spell1UsedCount: 0},
	{Spell2UsedCount: 0},
	{Spell3UsedCount: 0},
	{Spell4UsedCount: 0},
	{Spell5UsedCount: 0},
	{SpellSelected: 0},
	{GridSize: 0},
	{TotalSpells: 0},
	{Spell0GrowthLimit: 0},
	{Spell1GrowthLimit: 0},
	{Spell2GrowthLimit: 0},
	{Spell3GrowthLimit: 0},
	{Spell4GrowthLimit: 0},
	{Spell5GrowthLimit: 0},
	{TimesSpellsUsedPositionStorage: 0},
	{NewSpellAcquired: 0},
	{SpellBeingPickedUp: 0},
	{GridSize2: 0},
	{CheckingGrowth: 0},
	{RestartedGame: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Score: class extends self.ITextInstance {},
	Player: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Monster: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	InventoryGrid: class extends self.ITiledBackgroundInstance {},
	DebugText: class extends self.ITextInstance {},
	NewSpell: class extends self.IArrayInstance {},
	Wave: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Aoe: class extends self.ISpriteInstance {},
	SpellsCurrentlyKnown: class extends self.IArrayInstance {},
	Button2: class extends self.IButtonInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.IButtonInstance {},
	Audio: class extends self.IInstance {},
	Spell: class extends self.ISpriteInstance {},
	SpellGrowthLimits: class extends self.IArrayInstance {},
	TimesSpellsUsed: class extends self.IArrayInstance {},
	Array: class extends self.IArrayInstance {},
	SpellStages: class extends self.IArrayInstance {},
	OutsideOfGrid: class extends self.ISpriteInstance {},
	Ice: class extends self.ISpriteInstance {},
	Fireball: class extends self.ISpriteInstance {},
	FireballExplosion: class extends self.ISpriteInstance {},
	SpellDisplay: class extends self.ISpriteInstance {},
	Lightning: class extends self.ISpriteInstance {},
	LightningShock: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	SpellsEquipped: class extends self.IArrayInstance {},
	StartGame: class extends self.IButtonInstance {},
	Button3: class extends self.IButtonInstance {},
	Sparks: class extends self.ISpriteInstance {},
	Lightning2: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Wizard: class extends self.ISpriteInstance {},
	Axe: class extends self.ISpriteInstance {},
	IceShard: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	HelpButton: class extends self.IButtonInstance {},
	Play_Button: class extends self.ISpriteInstance {},
	Help_Button: class extends self.ISpriteInstance {},
	Titlescreenbackground: class extends self.ITiledBackgroundInstance {},
	LightningST: class extends self.ISpriteInstance {},
	BulletST: class extends self.ISpriteInstance {},
	AxeST: class extends self.ISpriteInstance {},
	FireballST: class extends self.ISpriteInstance {},
	IceShardST: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	DeathBackground: class extends self.ITiledBackgroundInstance {},
	Menu_Button: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {}
}